### ISSUE TITLE
Update deprecated or security warned dependencies

### ISSUE THREAD

**Issue by EnzoAlbornoz** [LauraBeatris/goeat-api#5]
I got deprecation warnings of Joi dependency when running the development server . Got security warnings when ran yarn audit too.

**Comment by EnzoAlbornoz** [comment]
Going to make a PR with updated dependencies.

**Comment by LauraBeatris** [comment]
Hi Enzo, 
Thanks for noticing the deprecated warning, i got some warning from github but i wasn't able to upgrade the packages because i'm currently doing a lot of integrations tests on another project that i'm development. 
Also, i'm currently deleting the Kue package, i decided to go with Bee Queue :)
Kue was giving some problems related to Redis connection and also deprecated dependencies installed with it.
